### ISSUE TITLE
Key Error at line 26? Maybe Spotify API got updated, please check?

### ISSUE THREAD

**Issue by livinhigh** [saulojoab/Spotify-To-Youtube#2]
https://github.com/saulojoab/Spotify-To-Youtube/blob/6511f4634a40a6aaa53df0c698b35b8e75739a20/spotifyToYoutube.py#L26

**Comment by livinhigh** [comment]
apparently the results dictionary doesnt have the "tracks" key anymore. I did a print on results.key() and  got this 

dict_keys(['href', 'items', 'limit', 'next', 'offset', 'previous', 'total'])

**Comment by livinhigh** [comment]
Ah i figured out you just have to change it to results["items"] instead!

**Comment by saulojoab** [comment]
@livinhigh so sorry it took me so long to see this, for some reason GitHub didn't notify me. 

glad it all worked out :)
